---
- name: Install build packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ build_packages }}"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages }}"

- name: Add primary user
  user:
    name: "{{ primary_user }}"
    groups: "{{ primary_user }}"

- name: Install vim
  git:
    repo: https://github.com/vim/vim
    dest: /root/vim
    version: master
  register: vim_cloned

- name: Check for vim
  command: "/usr/local/bin/vim"  # noqa 301
  become: true
  become_user: "{{ primary_user }}"
  register: vim_exists
  ignore_errors: true

- name: Compile vim
  command: "./configure --disable-gui \
    --disable-netbeans \
    --enable-multibyte \
    --enable-pythoninterp \
    --with-features=big \
    --with-python-config-dir=/usr/lib/python2.7/config"  # noqa 503
  args:
    chdir: /root/vim
  when: vim_cloned.changed or vim_exists.rc == 2
  register: vim_configure

- name: Install vim
  command: "make install"
  args:
    chdir: /root/vim
  when: vim_configure is changed

- name: Add vim autoload directory
  file:
    name: ~/.vim/autoload
    state: directory
  become: true
  become_user: "{{ primary_user }}"

- name: Install .vimrc
  get_url:
    url: https://raw.githubusercontent.com/nerdsvilleceo/.files/master/.vimrc
    dest: "~/.vimrc"
  become: true
  become_user: "{{ primary_user }}"

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.vim/autoload/plug.vim"
  become: true
  become_user: "{{ primary_user }}"

- name: Install vim-plug plugins
  command: vim +PlugInstall +qall  # noqa 301
  become: true
  become_user: "{{ primary_user }}"

- name: Remove build packages
  package:
    name: "{{ item }}"
    state: removed 
  with_items: "{{ build_packages }}"
